version: 2
updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: daily
    groups:
      storybook:
        patterns:
          - storybook
          - "@storybook/*"

      oclif:
        patterns:
          - oclif
          - "@oclif/*"

  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
