name: Pull Request
description: Thank you for your contribution to h5p-types! Your attention to detail and following of these guidelines will greatly assist the review process and help maintain the project's quality and consistency.
body:
  - type: markdown
    attributes:
      value: Please fill in each section completely. Thank you!

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: |
        Please provide a brief description of the purpose and context of this pull request.
        What problem does it address or what feature does it introduce?
        This will help reviewers understand the changes at a high level.
        Include any relevant background information or references to issues/feature requests.
      validations:
        required: true

  - type: textarea
    id: reviewers_guide
    attributes:
      label: 👀 Reviewer's Guide
      description: |
        Outline the key points that reviewers should focus on when examining this pull request.
        This could include specific changes made, potential impact on existing code, and any relevant testing or usage scenarios.
        Providing clear guidance will ensure efficient and effective reviews.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: |
        Please check all that apply.
        If you are unsure about any of these, don't hesitate to ask.
    options:
      - label: "**Pull Request Title and Description**: Is the pull request title concise and descriptive? Does the description provide enough context for reviewers to understand your changes?"
        required: true
      - label: "**Code Quality**: Have you ensured that your code adheres to the project's coding standards and conventions?"
        required: true
      - label: "**Review**: Have you gone through your own code changes to catch any potential issues before submitting for review?"
        required: true
      - label: "**Testing**: Have you added appropriate tests to cover the changes you've made? Are existing tests passing?"
        required: false
      - label: "**Documentation**: Have you updated relevant documentation (code comments, README, etc.) to reflect your changes?"
        required: false
