name: Check and validate package.json

on:
  - pull_request

jobs:
  check-package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - packages/h5p-types
          - packages/h5p-types-joubel-ui
          - packages/h5p-utils
          - packages/use-h5p

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build package
        run: bun run build --if-present
        working-directory: ${{ matrix.project }}

      - name: Check and validate ${{ matrix.project }}'s package.json
        uses: boyum/attw-action@v1
        with:
          working-directory: ${{ matrix.project }}
