name: Conventional Commits

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Validate commits
        uses: webiny/action-conventional-commits@v1.3.0
