name: Validate example projects

on:
  pull_request:

  push:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  run:
    name: Validate example projects

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        project:
          - h5p-content-type
          - h5p-content-type-react
          - h5p-resumable-content-type
          - h5p-widget

        typescript-version:
          - 4.7
          - 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build all packages
        run: npm run build

      - name: Set TypeScript version
        run: npm install typescript@${{ matrix.typescript-version }} --save-dev

      - name: Typecheck
        run: npm run typecheck --if-present
        working-directory: examples/${{ matrix.project }}

      - name: Test
        run: npm test --if-present
        working-directory: examples/${{ matrix.project }}

      - name: Lint
        run: npm run lint --if-present
        working-directory: examples/${{ matrix.project }}

      - name: Build
        run: npm run build --if-present
        working-directory: examples/${{ matrix.project }}
