name: Validate example projects

on: [push, pull_request]

jobs:
  run:
    name: Validate example projects

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        project:
          - h5p-content-type
          - h5p-widget

        typescript-version:
          - 4.9
          - 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install root dependencies
        uses: bahmutov/npm-install@v1

      - name: Install ${{ matrix.project }} dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: examples/${{ matrix.project }}

      - name: Set TypeScript version
        run: npm install typescript@${{ matrix.typescript-version }} --save-dev
        working-directory: examples/${{ matrix.project }}

      - name: Typecheck
        run: npm run typecheck --if-present
        working-directory: examples/${{ matrix.project }}

      - name: Test
        run: npm test --if-present
        working-directory: examples/${{ matrix.project }}

      - name: Lint
        run: npm run lint --if-present
        working-directory: examples/${{ matrix.project }}

      - name: Build
        run: npm run build --if-present
        working-directory: examples/${{ matrix.project }}
