name: Checks

on:
  pull_request:

  push:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  typecheck:
    name: Check types

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        typescript-version:
          - "5.0.4"
          - latest
          - beta
          - next

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install TypeScript
        run: npm install typescript@${{ matrix.typescript-version }}

      - name: Check types
        run: npm run typecheck

  validate-monorepo:
    name: Validate monorepo

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Validate monorepo
        run: npx sherif --ignore-dependency typescript

  lint:
    name: Check code style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check lint
        run: npm run code-style

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm run test
