name: Checks

on:
  pull_request:

  push:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  format:
    name: Check format

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check format
        run: npm run format:check

  typecheck:
    name: Check types

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check types
        run: npm run typecheck

  lint:
    name: Check lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check lint
        run: npm run lint:check

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build
