name: Checks

on:
  pull_request:

  push:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  format:
    name: Check format

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile --yarn

      - name: Check format
        run: bun run format:check

  typecheck:
    name: Check types

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        typescript-version:
          - 5.0.4
          - latest
          - beta
          - next

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile --yarn

      - name: Install TypeScript
        run: npm install typescript@${{ matrix.typescript-version }}

      - name: Check types
        run: bun run typecheck

  lint:
    name: Check lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile --yarn

      - name: Check lint
        run: bun run lint:check

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile --yarn

      - name: Build
        run: bun run build
