name: Checks

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  format:
    name: Check format

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check format
        run: npm run format:check

  typecheck:
    name: Check types

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        typescript-version:
          - 4.5
          - next
          - latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install TS version
        run: npm install typescript@${{ matrix.typescript-version }}

      - name: Check types
        run: npm run typecheck

  lint:
    name: Check lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check lint
        run: npm run lint:check
